name: field_timestamp_camera
description: Field Timestamp Camera with Editable Address/Time, Job + Crew Tagging
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  geolocator: ^10.1.0
  http: ^1.1.0
  intl: ^0.18.1
  image: ^4.1.7
  path_provider: ^2.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
